name: Build and Deploy to dockerhub

on: 
  push: 
    branches: 
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile.userApp
          push: true
          tags: rukshdev/project_paytm_app1:latest
        
      - name: Verify Pushed Image
        run: docker pull rukshdev/project_paytm_app1:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker pull rukshdev/project_paytm_app1:latest
            sudo docker stop web-app || true
            sudo docker rm web-app || true
            sudoe docker run -d --name web-app -p 3005:3000 rukshdev/project_paytm_app1:latest 
